actions:
  - name: addNumbers
    definition:
      kind: synchronous
      handler: http://localhost:3000/api/add
    permissions: []
custom_types:
  enums: []
  input_objects: []
  objects:
    - name: AddResult
      relationships: []
  scalars: []
